# Generated by Django 3.1 on 2020-08-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=400)),
                ('text1', models.TextField()),
                ('image1', models.ImageField(upload_to='home/images')),
                ('about_heading', models.CharField(max_length=400)),
                ('about_text', models.TextField()),
                ('about_poster', models.ImageField(upload_to='home/images')),
                ('about_video', models.FileField(upload_to='home/videos')),
                ('our_way_heading', models.CharField(max_length=400)),
                ('forex_text', models.TextField()),
                ('crypto_text', models.TextField()),
                ('learning_heading', models.CharField(max_length=400)),
                ('learning_text', models.TextField()),
                ('learning_poster', models.ImageField(upload_to='home/images')),
                ('learning_video', models.FileField(upload_to='home/videos')),
                ('learning_item1', models.CharField(max_length=400)),
                ('learning_item2', models.CharField(max_length=400)),
                ('learning_item3', models.CharField(max_length=400)),
                ('learning_item4', models.CharField(max_length=400)),
                ('testimonial_heading', models.CharField(max_length=400)),
                ('testimonial_text', models.TextField()),
                ('testimonial_image1', models.ImageField(upload_to='home/images')),
                ('testimonial_image2', models.ImageField(upload_to='home/images')),
                ('testimonial_image3', models.ImageField(upload_to='home/images')),
                ('facebook_url', models.URLField()),
                ('twitter_url', models.URLField()),
                ('instagram_url', models.URLField()),
            ],
        ),
    ]
