# Generated by Django 3.1 on 2020-08-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=400)),
                ('poster1', models.ImageField(upload_to='testimonial/images')),
                ('poster2', models.ImageField(upload_to='testimonial/images')),
                ('poster3', models.ImageField(upload_to='testimonial/images')),
                ('video1', models.FileField(upload_to='testimonial/videos')),
                ('video2', models.FileField(upload_to='testimonial/videos')),
                ('video3', models.FileField(upload_to='testimonial/videos')),
                ('pips_in_profit', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('trades_per_week', models.CharField(max_length=20)),
            ],
        ),
    ]
