# Generated by Django 3.1 on 2020-08-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_template', '0004_calltime_getstarted_schedulecall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calltime',
            options={'get_latest_by': ['-pk']},
        ),
    ]
