# Generated by Django 3.1 on 2020-08-13 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=400)),
                ('phase1_description', models.TextField()),
                ('phase2_description', models.TextField()),
                ('phase3_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhaseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('phase 1', 'phase 1'), ('phase 2', 'phase 2'), ('phase 3', 'phase 3')], max_length=20)),
                ('poster', models.ImageField(upload_to='images/phase')),
                ('video', models.FileField(upload_to='videos/phase')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcommingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase1_progress', models.DecimalField(decimal_places=1, max_digits=3)),
                ('phase2_progress', models.DecimalField(decimal_places=1, max_digits=3)),
                ('phase3_progress', models.DecimalField(decimal_places=1, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
