# Generated by Django 3.1 on 2020-08-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='upcommingevent',
            options={'ordering': ['-date']},
        ),
    ]
