# Generated by Django 3.1 on 2020-08-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200813_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='upcommingevent',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='userdashboard',
            name='phase1_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdashboard',
            name='phase2_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdashboard',
            name='phase3_progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
