# Generated by Django 3.1 on 2020-08-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200813_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='dashboard',
            name='phase1_sub_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='phase1_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='phase2_sub_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='phase2_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='phase3_sub_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='phase3_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
