# Generated by Django 3.1 on 2020-08-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_phasecontent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasecontent',
            name='description',
            field=models.TextField(default='phase content description '),
            preserve_default=False,
        ),
    ]
