# Generated by Django 3.1 on 2020-08-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_trainingcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('PNG', 'PNG'), ('PDF', 'PDF'), ('PPT', 'PPT')], max_length=20)),
                ('file', models.FileField(upload_to='materials/files')),
            ],
        ),
    ]
