# Generated by Django 3.1 on 2020-08-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-pk']},
        ),
    ]
