# Generated by Django 3.1 on 2020-09-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200820_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phasecontent',
            options={'ordering': ['pk']},
        ),
    ]
