# Generated by Django 3.1.1 on 2020-09-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=400)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
    ]
